AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is the VPC Endpoin t to keep the API gateway Private'
Parameters: 
  AlcolizerVPC:
    Type: String
    Default: vpc-0159fa80f47d2d416
    Description: The name of VPC that the application 
    MinLength: '1'
    ConstraintDescription: This parameter is required    
Resources:
  AlcolizerAPIGatewayVPCEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: 'Allow'
            Principal: '*'
            Action: '*'
            Resource: '*'
      PrivateDnsEnabled : true
      VpcEndpointType: Interface
      SubnetIds:
        - 'subnet-08e5a736badd6854d'
        - 'subnet-023df08ac200dbeca'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.execute-api'
      VpcId: !Ref AlcolizerVPC
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow https to API Gateway
        VpcId: !Ref AlcolizerVPC
        SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 10.0.0.0/8
        - IpProtocol: -1
          SourceSecurityGroupId: 'sg-097bb13397b7fdbbb'
        SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
Outputs:
  StackVPC:
    Description: The ID of the VPC Endpoint
    Value: !Ref AlcolizerAPIGatewayVPCEndpoint   

